# @package _global_

transfer_method: FINETUNE
embedder_finetuning: LAYERWISE_LR
embedder_features: CNN_BACKBONE_PLUS_AVG_POOLING

head: LINEAR
head_dropout: 0.25
head_normalize: true

batch_size: 512
num_epochs: 100
warmup_epochs: 10
early_stopping_patience: -1

lr: -1.25
layerwise_lr_mult: 0.7
weight_decay: -2.25
feature_space_reg_alpha: 0
start_point_reg_alpha: 0

embedder_batchnorm_eval_mode: false
embedder_dropout_eval_mode: false
embedder_replace_unseen_packets_threshold: 1